hash-format = "sha256"

[[files]]
file = "config/Geyser-Fabric/config.yml"
hash = "d0c32c7ce41174ebc308f990da79eec539fabd537599a6e26b8aa1f3cf1d88a4"

[[files]]
file = "config/Geyser-Fabric/packs/Bedrock Tweaks.mcpack"
hash = "9a9109ff3e94ee8dbf1d57099caa32fa7864a4fa6a821af967ed87e63d89e027"

[[files]]
file = "config/Veinminer/blocks.json"
hash = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"

[[files]]
file = "config/Veinminer/groups.json"
hash = "f84fe450f48469dfd9f95ce38bbeffc85ddba4593a8d0eece4fadf7a12a4befd"

[[files]]
file = "config/Veinminer/settings.json"
hash = "633c7cc31ab68b71c6c073c1e4655681c152240b3cb53c3057f7e8cce01d9720"

[[files]]
file = "config/sparsestructures.json5"
hash = "d4e931281edd1a7f32c43caca4743239dee3c79404fcfdce42d7f2acdf3c4344"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "f06b2452cec58f6357c69271668fbf3f50133a9a92375b117439e9671a62225c"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "242060ec1e0b85b76bfdad7daf8518505a6793ee666f76e9290175f6bc64b843"

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "a43e3d76464a16015d62ba08d51da734f92377f0889c3984656d6d5739d284b2"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "d36d0104f40c65ec6e8f7b37c33662ebe57f06e1c3864f9458fd4ea534f4af6a"
metafile = true
