name = "JacobCXDev's Pack"
author = "JacobCXDev"
version = "distanthorizons"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9033a880e2a6017f53ed61e2e11e11df6d39b0133dfb59fde5410280630de4f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9"]
