name = "JacobCXDev's Pack"
author = "JacobCXDev"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1117acc88db9efd6368d4b9b1cd0b17ff160fc7a3e836fd1a13ac4e1066ab1ad"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5", "1.21.6", "1.21.7", "1.21.8", "1.21.9"]
